version: '3'
  
services:
  gender_data:
    image: vre4eic/gender-demo-data
    build: .
    volumes:
      - gender_swish_volume:/data

  gender_rserve:
    restart: always
    image: swipl/rserve
    network_mode: "none"
    volumes:
    - gender_r_volume:/rserve

  gender_swish_initalize:
    image: vre4eic/swish
    volumes:
      - gender_swish_volume:/data
    depends_on:
      - gender_rserve
      - gender_data
    command: --add-config auth_http.pl --add-config data.pl --add-config network.pl --add-config logging.pl --add-config provenance.pl --add-config rdf.pl --add-config r_serve.pl --add-config user_profile.pl 

  gender_swish:
    restart: always
    image: vre4eic/swish
    ports:
      - 3050:3050
    volumes:
      - gender_swish_volume:/data
      - gender_r_volume:/rserve
    depends_on:
      - gender_data
      - gender_rserve
      - gender_swish_initalize

volumes:
        gender_r_volume:
        gender_swish_volume:
